# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.
[[main]]
  name = "about"
  pageRef = "about"
  weight = 10
[[main]]
  name = "services"
  pageRef = "services"
  weight = 20
[[main]]
  name = "pricing"
  pageRef = "pricing"
  weight = 30
[[main]]
  name = "blog"
  pageRef = "blog"
  weight = 40
[[main]]
  name = "support <i class='fas fa-external-link-alt'></i>"
  url = "https://support.embrcollab.com/"
  weight = 50

[[footer]]
  name = "terms"
  url = "https://cdn.embrcollab.com/file/cdn-web-development/embr-collab-site/docs/embr-collab-terms-and-conditions-v1.0.pdf"
  weight = 10
[[footer]]
  name = "privacy policy"
  url = "https://cdn.embrcollab.com/file/cdn-web-development/embr-collab-site/docs/embr-collab-privacy-policy-v1.0.pdf"
  weight = 20
[[footer]]
  name = "sitemap"
  url = "/sitemap.xml"
  weight = 30